// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1a0ca869-f280-4043-a33f-732d56f6f063";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLocationChange();

String location;
float humidity;
float pressure;
float temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(location, READWRITE, 3 * SECONDS, onLocationChange);
  ArduinoCloud.addProperty(humidity, READ, 3 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 3 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 3 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
